name = "freelanceos-leads-worker"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "freelanceos-leads"
database_id = "fdd31c4f-c38d-42a7-87f7-2fd4094eed06"

[vars]
ENVIRONMENT = "production"
